name: reminder_app
description: A minimal Reminder App demonstrating local notifications with flutter_local_notifications and DateTimePicker.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^12.0.4
  date_time_picker: ^2.1.0
  timezone: ^0.9.0
  flutter_native_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
